### ISSUE TITLE
Allow for `topic.line` to be a function?

### ISSUE THREAD

**Issue by spitlo** [okaybenji/text-engine#16]
First of all, thank’s for a really nice and customizable engine!

I’ve reached a point in a game where I would really benefit from having the `line` in a topic be dynamic. If, say, there’s a timer in the game, or if the player at some point learns a character’s name, it would be nice if the same topic, when picked a second time, would mirror the current value of the timer, or use the newly learned name of the character (I hope that explanation makes sense).

I realize I could  probably do this by overriding the `talkToOrAboutX` function, but there’s so much logic in it that I rather keep the original one from `index.js`.

Perhaps there is another way to accomplish this? I see that `character.topics` can be a function, but that seems cumbersome if you have a lot of topics for a character.

**Comment by okaybenji** [comment]
Hi, @spitlo, and thank you for the feature request! Actually, this feature exists but needs to be documented. I will put that on my to-do list. Your line just needs to return a string, which `println` will then add to the DOM.

If you'd like to see where this was added, here's the commit: https://github.com/okaybenji/text-engine/commit/68c56a4716f28f47f049f1310b10cae1295bf9a7

And you can see an example of how to use it in the "Ur Dead" demo disk on line 636:

https://github.com/okaybenji/text-engine/blob/master/game-disks/ur-dead.js#L636

If you have any questions about how to use this or run into any trouble, please let me know!

**Comment by spitlo** [comment]
Thanks! I had an inkling there was something like that in Ur Dead but I couldn’t find it. I could have just tried I guess 😊 

Closing this.
