### ISSUE TITLE
Clear text

### ISSUE THREAD

**Issue by TelegramXPlus** [okaybenji/text-engine#26]
In my opinion it would be good if there was a command to clear the current displayed text, for instance when there's a map represented as an ASCII image and we want to update the map since we've moved to another direction. Also it would be a good idea if we could display the text in a manner where each character is delayed.

**Comment by Bharat0112** [comment]
Its bit late, and I'm not sure I completely understand, but still....

I am no programmer, but I have added the code in index.js file as below.
(Here we are defining new command called 'map'.)

`
let map = (id) => {
  const room = getRoom(disk.roomId);

  if (!room) {
    println(`Something xyz.....`);
    return;
  }
  println(room.img, 'img');
};`

Then find the line - let commands = [
There are commands listed out there, such as save,go,talk etc. Add the word map there.

Now open your disk file where game text are, say demo.js.
Under room add this
img: ``,
put your ascii map inside the quotes.

You need to add this in every room where you need the map.
Now, while playing the game, type map to see the map.

You can add Hint command the same way.
