### ISSUE TITLE
Restart game (fresh)

### ISSUE THREAD

**Issue by tvb** [okaybenji/text-engine#30]
Hi @okaybenji,

Would it be possible to add a method to restart a game from fresh. Deleting the history/commands and possibly also clearing any local saved game.

**Comment by okaybenji** [comment]
You can simply add a custom command to your game. Stick this in the HTML file:

```
<script>
  const clearScreen = () => document.querySelector('#output').innerHTML = '';
  const reload = () => {
    clearScreen();
    loadDisk();
  };
  commands[0] = Object.assign(commands[0], {reload});
</script>
```

**Comment by tvb** [comment]
Yes, that seems to work 👍🏻
