### ISSUE TITLE
Always LOOK when you re-enter the room

### ISSUE THREAD

**Issue by drrak** [okaybenji/text-engine#36]
_Translator:_
Great engine. I like everything very much, except for the abbreviated description after re-entering a previously visited room. Because of this, I often have to enter LOOK.

Can this be easily changed?

**Comment by dthigpen** [comment]
If your use case is to print the full description when entering each roon, could use the `onEnter` hook? Like so:
```js
{
    id: 'roomid',
    name: 'Room Name',
    desc: `Long description of the room`,
    onEnter: () => {
        const room = getRoom('roomid')
        if(room.visits > 1) {
            println(room.desc)
        }
    }
}
```
On the first visit, the description will be printed by the engine. On successive visits, the description will be printed by this `onEnter` hook.
