### ISSUE TITLE
Support endGame method

### ISSUE THREAD

**Issue by okaybenji** [okaybenji/text-engine#5]
It would be handy to be able to pass an `endGame` method on the configuration object for environments like Node so the process may exit. Could maybe just let the game developer have access to this method in use functions. Perhaps in the example game, for instance, using the door could first move the player to the final room and then end the game.

**Comment by Dojaykabumbah** [comment]
Assistance with crypto conversion 😄 plz benji

**Comment by Dojaykabumbah** [comment]
> #
[4ff2916e7d52bde77d4be241e3dd126249ad34aa09a80b8c08b06508e7bfd7d4.txt](https://github.com/okaybenji/text-engine/files/12208327/4ff2916e7d52bde77d4be241e3dd126249ad34aa09a80b8c08b06508e7bfd7d4.txt)
``
